### ISSUE TITLE
Value feeding to placeholder

### ISSUE THREAD

**Issue by PowerToThePeople111** [lifeomic/sparkflow#34]
Hi all,

I am trying to train the following multilabeling model and want to play around with the activation and losses functions to see their impact on the final model: 

```
def nn_model2(featuresCount, classCount, hiddenNeuronCount = -1):
    if hiddenNeuronCount == -1:
        hiddenNeuronCount = classCount * 5

    x = tf.placeholder(tf.float32, shape=[None, featuresCount], name='x')
    y = tf.placeholder(tf.float32, shape=[None, classCount], name='y')

    w1 = tf.Variable(tf.random_uniform([featuresCount, hiddenNeuronCount], minval=0, maxval=0.1))
    b1 = tf.Variable(tf.random_uniform([hiddenNeuronCount], minval=0, maxval=0.1))
    in1 = tf.add(tf.matmul(x, w1), b1)
    act1 = tf.nn.relu(in1)

    w2 = tf.Variable(tf.random_uniform([hiddenNeuronCount, classCount], minval=0, maxval=0.1))
    b2 = tf.Variable(tf.random_uniform([classCount], minval=0, maxval=0.1))
    in2 = tf.add(tf.matmul(act1, w2), b2)
    act2 = tf.nn.sigmoid_cross_entropy_with_logits(logits=in2, labels=y, name='out')
    
    loss = tf.losses.mean_squared_error(y, act2) 

    return loss
```

Many of the partitions get fully calculated generating the expected loss printouts. One worker though produces the following output and makes the job fail:

```
Original stack trace for 'y':
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "mnt/yarn/usercache/hadoop/appcache/application_1562682440747_0169/container_1562682440747_0169_01_000011/pyspark.zip/pyspark/daemon.py", line 195, in <module>
  File "mnt/yarn/usercache/hadoop/appcache/application_1562682440747_0169/container_1562682440747_0169_01_000011/pyspark.zip/pyspark/daemon.py", line 170, in manager
  File "mnt/yarn/usercache/hadoop/appcache/application_1562682440747_0169/container_1562682440747_0169_01_000011/pyspark.zip/pyspark/daemon.py", line 73, in worker
  File "mnt/yarn/usercache/hadoop/appcache/application_1562682440747_0169/container_1562682440747_0169_01_000011/pyspark.zip/pyspark/worker.py", line 372, in main
    process()
  File "mnt/yarn/usercache/hadoop/appcache/application_1562682440747_0169/container_1562682440747_0169_01_000011/pyspark.zip/pyspark/worker.py", line 367, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2499, in pipeline_func
  File "usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2499, in pipeline_func
  File "usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 352, in func
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/sparkflow/tensorflow_async.py", line 99, in <lambda>
    return dataset.rdd.mapPartitions(lambda x: predict_func(x, mod_json, out, mod_weights, inp, tf_output, tf_input, tf_dropout, to_keep_dropout)).toDF()
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/sparkflow/ml_util.py", line 66, in predict_func
    tf.train.import_meta_graph(graph)
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1449, in import_meta_graph
    **kwargs)[0]
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1473, in _import_meta_graph_with_return_elements
    **kwargs))
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 857, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 443, in import_graph_def
    _ProcessNewOps(graph)
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 236, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3751, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3751, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3641, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:452)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:588)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:571)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:406)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
        at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
        at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
        at org.apache.spark.api.python.PythonRDD$$anonfun$3.apply(PythonRDD.scala:153)
        at org.apache.spark.api.python.PythonRDD$$anonfun$3.apply(PythonRDD.scala:153)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2039)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2027)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2026)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2026)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:966)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:966)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:966)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2260)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2209)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2198)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:777)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
        at org.apache.spark.api.python.PythonRDD$.runJob(PythonRDD.scala:153)
        at org.apache.spark.api.python.PythonRDD.runJob(PythonRDD.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/hadoop/anaconda3/envs/pySpark/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'y' with dtype float and shape [?,2]
         [[{{node y}}]]
```

I tested the training data and it contains no rows without labels. So y should always be of the requested shape, should it not? Also the other successful running tasks seem to indicate that the data fits the network.

Is there something I miss?

Best,

PS: I also tested the sigmoid loss function, but that also produced an exception.

**Comment by PowerToThePeople111** [comment]
Ok, I found out myself how to deal with it: You must take care, that spark stores a **DenseVector** in the DF which you gonna use for training with Sparkflow. Otherwise you will get error messages which complain about feeding wrong tensorshapes to either input or labels.
